kind: pipeline
name: default

steps:
  - name: build-api-image
    image: plugins/docker
    settings:
      username:
        from_secret: docker-hub-username
      password:
        from_secret: docker-hub-password
      repo: yujiangshui/happy-fake-file-server
      dockerfile: Dockerfile
      tags:
        - ${DRONE_COMMIT}
        - latest
